zenn-dev/zenn-editor

packages/zenn-cli/articles/example.md, packages/zenn-cli/articles/no-frontmatters.md, packages/zenn-cli/articles/xss.md, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/md.ts, yarn.lock
=> feat: allow inline comment

packages/zenn-cli/cli/constants.ts, packages/zenn-cli/cli/new-article.ts
- Add a guidance for `--published` option in the help message
- Make `--published` option `boolean` flag
=> fixup published option

packages/zenn-cli/cli/constants.ts, packages/zenn-cli/cli/new-article.ts
=> add "machine-readable" option to parse output by scripts

packages/zenn-cli/pages/_app.tsx
=> fix: prevent scroll when hot reloading

packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json
npm でみたときに GitHub へ辿れずMOTTAINAIと思いました。
なにか意図がるのだとしたら容赦なく Reject  してください！
※ zenn-cli には意図的に追加してません
=> リポジトリ情報を追加

packages/zenn-embed-elements/src/classes/katex.ts
close https://github.com/zenn-dev/zenn-community/issues/304
=> KaTeX のバージョンを v0.12 から v0.13 へ更新

.github/workflows/lint.yml, package.json, packages/zenn-cli/.eslintrc.yml, packages/zenn-cli/package.json, packages/zenn-cli/src/client/components/Routes.tsx, packages/zenn-embed-elements/.eslintrc.yml, packages/zenn-embed-elements/package.json, packages/zenn-embed-elements/src/classes/mermaid.ts, packages/zenn-markdown-html/.eslintrc.yml, packages/zenn-markdown-html/__tests__/br.test.ts, packages/zenn-markdown-html/__tests__/custom.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/md-br.ts, packages/zenn-markdown-html/src/utils/md-container.ts, packages/zenn-markdown-html/src/utils/md-custom-block.ts, packages/zenn-markdown-html/src/utils/md-katex.ts
各パッケージのeslintのwarningsをひとまず解消しました。
=> eslintの警告を解消

packages/zenn-cli/articles/math.md, packages/zenn-content-css/src/_embed.scss
Resolves https://github.com/zenn-dev/zenn-community/issues/327
=> KaTeXのインライン記法であっても長さに応じて横スクロールするように

.github/PULL_REQUEST_TEMPLATE.md, lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_embed.scss, packages/zenn-embed-elements/package.json, packages/zenn-embed-elements/src/classes/mermaid.ts, packages/zenn-markdown-html/package.json, yarn.lock
=> release: mermaid のheightが不自然にならないようワークアラウンド対応 / bump cheerio

packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/src/_embed.scss, packages/zenn-content-css/src/_footnotes.scss, packages/zenn-markdown-html/src/index.ts
=> 本文のスタイルの微調整

packages/zenn-cli/articles/mermaid.md, packages/zenn-embed-elements/src/classes/mermaid.ts
mermaid.jsのバージョンアップ。
Resolves: https://github.com/zenn-dev/zenn-community/issues/353
=> Bump up mermaid.js from 8.12 to 8.13

lerna.json, packages/zenn-cli/articles/mermaid.md, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/src/_footnotes.scss, packages/zenn-embed-elements/package.json, packages/zenn-embed-elements/src/classes/mermaid.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/index.ts
=> release: 本文のスタイルの微調整 / mermaid.jsのバージョンアップ

packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/src/_prism.scss, packages/zenn-content-css/src/index.scss
=> コードブロックのスタイルを微調整

lerna.json, packages/zenn-cli/articles/math.md, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/dollar.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/md-katex.ts, yarn.lock
ref:
https://github.com/zenn-dev/zenn-community/issues/368
=> release: 数式検出の正規表現を修正、bump nanoid

packages/zenn-cli/jest.config.client.js, packages/zenn-cli/jest.config.server.js, packages/zenn-cli/package.json, packages/zenn-markdown-html/jest.config.js, packages/zenn-markdown-html/package.json, yarn.lock
[@swc/jest](https://github.com/swc-project/jest) を使ってテストを高速化した。
Resolves #240 
=> feat: @swc/jestを使ってテストを高速化

packages/zenn-cli/package.json, yarn.lock
=> chore: bump node-fetch

packages/zenn-embed-components/.storybook/main.js, packages/zenn-embed-components/package.json, packages/zenn-embed-components/tsconfig.json, yarn.lock
=> feat: emotionを使えるように環境構築した

packages/zenn-embed-components/package.json, packages/zenn-embed-components/src/components/mermaid/index.tsx, packages/zenn-embed-components/src/components/mermaid/mermaid.stories.tsx, yarn.lock
=> feat: [skip ci]mermaidレンダリングまで

packages/zenn-embed-components/package.json, packages/zenn-embed-components/src/components/gist/EmbedGistError.tsx, packages/zenn-embed-components/src/components/gist/EmbedGistLoading.tsx, packages/zenn-embed-components/src/components/gist/gist.stories.tsx, packages/zenn-embed-components/src/components/gist/index.tsx
Github Gist の埋め込みコンポーネントを実装しました。
=> feat: Gistの埋め込みコンポーネントを実装した

packages/zenn-markdown-html/__tests__/link.test.ts, packages/zenn-markdown-html/src/utils/url-matcher.ts
=> ツイート埋め込みの正規表現を調整

packages/zenn-markdown-html/package.json, yarn.lock
- https://github.com/PrismJS/prism/pull/3341
- zennではCommand Line Pluginを使っていないため影響がないが、ユーザーの環境でもアラートが表示されてしまうことを防ぐため修正
=> prism.jsのアップデート

packages/zenn-content-css/src/_content.scss
- ref: https://github.com/zenn-dev/zenn-community/issues/383
=> タスクリストでチェックの下にドットが見えてしまう問題の修正

packages/zenn-cli/src/client/components/BodyContent.tsx, packages/zenn-cli/src/client/components/PrintDetailsOpener.tsx, packages/zenn-cli/src/client/components/articles/show.tsx
印刷時に details を開くように修正しました。
Resolves #267 
=> feat: 印刷時にdetailsを開くようにした

packages/zenn-content-css/src/_embed.scss, packages/zenn-content-css/src/_footnotes.scss
=> 未使用のcssを削除

packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx, packages/zenn-cli/src/client/lib/validator.ts
articleのfrontmatterのpublished_atをcamelCase（publishedAt）に修正します。
=> published_atをcamelCaseに修正

packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx, packages/zenn-cli/src/client/lib/validator.ts, packages/zenn-cli/src/common/types.ts
他の項目との統一のため、publishedAtをsnake_caseに修正
=> publishedAtをsnake_caseに修正

lerna.json, packages/zenn-cli/articles/code-fence.md, packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/articles/math.md, packages/zenn-cli/articles/mermaid.md, packages/zenn-cli/articles/xss.md, packages/zenn-cli/package.json, packages/zenn-cli/src/client/components/ValidationErrors.tsx, packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx, packages/zenn-cli/src/client/lib/validator.ts, packages/zenn-cli/src/common/types.ts, packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md, packages/zenn-cli/src/server/__tests__/lib/helper.test.ts, packages/zenn-cli/src/server/lib/articles.ts, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/helper.ts, yarn.lock
changes: 
- #296
- #294
- #298
- #299
=> release v0.1.111

yarn.lock
- ビルド
- プレビュー起動
をローカルで確認しました。
Resolves https://github.com/zenn-dev/zenn-editor/security/dependabot/25
=> dep: got のバージョンをあげた

lerna.json, packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/package.json, packages/zenn-cli/src/client/__tests__/lib/validator.test.ts, packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx, packages/zenn-cli/src/client/index.html, packages/zenn-cli/src/client/lib/validator.ts, packages/zenn-cli/src/common/types.ts, packages/zenn-cli/webpack.server.js, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, yarn.lock
changes:
- https://github.com/zenn-dev/zenn-editor/pull/309
- https://github.com/zenn-dev/zenn-editor/pull/307
- https://github.com/zenn-dev/zenn-editor/pull/311
=> release v0.1.114

packages/zenn-cli/README.md
READMEに記載の通りだと以下のように不正な文字数として扱われてしまうので、12文字以上に変えました。
```sh
$ yarn zenn new:article --slug foo-bar-baz
yarn run v1.22.19
$ node dist/server/zenn.js new:article --slug foo-bar-baz
error: slugの値（foo-bar-baz）が不正です。小文字の半角英数字（a-z0-9）、ハイフン（-）、アンダースコア（_）の12〜50字の組み合わせにしてください
✨  Done in 0.69s.
$ yarn zenn new:book --slug foo-bar-baz
yarn run v1.22.19
$ node dist/server/zenn.js new:book --slug foo-bar-baz
error: slugの値（foo-bar-baz）が不正です。小文字の半角英数字（a-z0-9）、ハイフン（-）、アンダースコア（_）の12〜50字の組み合わせにしてください
✨  Done in 0.75s.
```
=> chore: Fixed command argument character length.

lerna.json, packages/zenn-cli/README.md, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, yarn.lock
https://github.com/zenn-dev/zenn-editor/pull/312
https://github.com/zenn-dev/zenn-editor/pull/313
=> release v0.1.115

lerna.json, packages/zenn-cli/package.json, packages/zenn-cli/src/client/lib/validator.ts, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, yarn.lock
https://github.com/zenn-dev/zenn-editor/pull/317
https://github.com/zenn-dev/zenn-editor/pull/319
=> release v0.1.116

packages/zenn-cli/articles/embed-examples.md, packages/zenn-markdown-html/src/utils/md-custom-block.ts
iframeに指定されている不要なattributeを整理しました。
=> iframeのattributesを整理

packages/zenn-markdown-html/__tests__/basic.test.ts
docId（脚注の重複リンク回避） に関するテストを追加した
https://github.com/zenn-dev/zenn-editor/pull/329
↑これの修正に対するテスト
=> add test for docId

package.json, packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx, yarn.lock
[publicaiton_name が設定されているときのみプロパティを表示するように修正](https://github.com/zenn-dev/zenn-editor/commit/3cdc26f5b18a44eb6397f7b4ec2eef5c4240fe47)
Resolves https://github.com/zenn-dev/zenn-editor/issues/339
=> publicaiton_name が設定されているときのみプロパティを表示するように修正

lerna.json, packages/zenn-cli/articles/embed-examples.md, packages/zenn-cli/articles/link-card.md, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/README.md, packages/zenn-markdown-html/__tests__/custom.test.ts, packages/zenn-markdown-html/__tests__/link.test.ts, packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/index.ts, packages/zenn-markdown-html/src/markdown-to-simple-html.ts, packages/zenn-markdown-html/src/utils/md-custom-block.ts, packages/zenn-markdown-html/src/utils/md-link-attributes.ts, packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts, packages/zenn-markdown-html/src/utils/url-matcher.ts, yarn.lock
changes:
- #355 
- #349
- #354
=> release: v0.1.122

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_embed.scss, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/custom.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/md-custom-block.ts
pr:
- https://github.com/zenn-dev/zenn-editor/pull/357
=> release 0.1.123

packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts, packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts, packages/zenn-markdown-html/src/utils/url-matcher.ts
=> FigmaとblueprintUEの埋め込み要素の正規表現を修正

packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts, packages/zenn-markdown-html/src/utils/url-matcher.ts
=> fix: テストエラーを修正

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/url-matcher.ts
=> release v0.1.125

packages/zenn-markdown-html/src/utils/embed-helper.ts
=> fix: 埋め込み要素のタイプ判定をより安全な形へ修正

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/embed-helper.ts
=> release v0.1.127

packages/zenn-cli/articles/embed-examples.md, packages/zenn-cli/articles/zenn-embed-examples.md, packages/zenn-markdown-html/__tests__/custom.test.ts, packages/zenn-markdown-html/__tests__/xss.test.ts, packages/zenn-markdown-html/src/utils/url-matcher.ts
Resolves https://github.com/zenn-dev/zenn-community/issues/433#issuecomment-1265847341
フレームIDを指定して埋め込むケースにも対応できるよう、正規表現を修正しました。
=> figma のフレームを埋め込めるように正規表現を修正した

lerna.json, packages/zenn-cli/articles/embed-examples.md, packages/zenn-cli/articles/zenn-embed-examples.md, packages/zenn-cli/package.json, packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx, packages/zenn-cli/src/client/lib/validator.ts, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/custom.test.ts, packages/zenn-markdown-html/__tests__/xss.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/url-matcher.ts
=> release v0.1.129

CONTRIBUTING.md, README.md, packages/zenn-embed-elements/README.md
=> 埋め込みコンテンツに関するドキュメントを最新の内容に修正

CONTRIBUTING.md, README.md, lerna.json, packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/src/_message.scss, packages/zenn-embed-elements/README.md, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json
=> release v0.1.130

.github/workflows/policy-comment.yml
ロジックに影響がない、開発作業です、いくつかの修正をマージする可能性があります。
=> chore: 権限設定

package.json
詳細はこちら
[lockfile-lintを使うとOSSのnpmパッケージでロックファイルにマルウェアを仕込まれるリスクを軽減できる - zenn](https://zenn.dev/catnose99/scraps/2ba4ac2d285255)
=> lockfile-lintの導入

README.md, lerna.json, packages/zenn-cli/README.md, packages/zenn-cli/package.json, packages/zenn-content-css/README.md, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_message.scss, packages/zenn-content-css/test.html, packages/zenn-embed-elements/README.md, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/README.md, packages/zenn-markdown-html/__tests__/custom.test.ts, packages/zenn-markdown-html/__tests__/link.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/md-container.ts, packages/zenn-validator/README.md, packages/zenn-validator/package.json, yarn.lock
=> release v0.1.133

lerna.json, packages/zenn-cli/package.json, packages/zenn-cli/vite.config.ts, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_embed.scss, packages/zenn-content-css/src/_message.scss, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/sanitizer.ts, packages/zenn-validator/package.json, packages/zenn-validator/tsconfig.json
**changes**
- #398
- #399
- #400
=> release v0.1.134 

.github/workflows/publish-canary.yml, .github/workflows/publish-latest.yml
release の workflow が失敗する問題を修正。
=> fix: リリースの workflow を修正

.github/workflows/publish-latest.yml, lerna.json
=> fix: lerna version コマンドがエラーになる問題を修正

lerna.json, packages/zenn-cli/package.json, packages/zenn-cli/src/server/lib/server.ts, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
=> release v0.1.139

.github/PULL_REQUEST_TEMPLATE.md
=> docs: Pull Request のテンプレートの見出しレベルを調整

.github/PULL_REQUEST_TEMPLATE.md, lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_prism.scss, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
=> release v0.1.140

packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/src/client/components/TopicList.tsx, packages/zenn-cli/src/client/global.css
機能要望でディスカッションできていない状態ですが、小さな変更なので実装してみました。
Resolves #430
=> feat: トピックにリンクを追加

LICENSE, README.md, packages/zenn-cli/LICENSE, packages/zenn-content-css/LICENSE, packages/zenn-embed-elements/LICENSE, packages/zenn-markdown-html/LICENSE, packages/zenn-model/LICENSE
- LICENSE ファイルをルートと各パッケージのディレクトリに追加
- README 内の表現がライブラリの意図と合わない可能性があるので修正
=> docs: LICENSE ファイルの追加と README 内の表現を修正

LICENSE, README.md, lerna.json, packages/zenn-cli/LICENSE, packages/zenn-cli/articles/exampleexample.md, packages/zenn-cli/package.json, packages/zenn-cli/src/client/components/TopicList.tsx, packages/zenn-cli/src/client/global.css, packages/zenn-content-css/LICENSE, packages/zenn-content-css/package.json, packages/zenn-embed-elements/LICENSE, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/LICENSE, packages/zenn-markdown-html/package.json, packages/zenn-model/LICENSE, packages/zenn-model/package.json
**changes**
- https://github.com/zenn-dev/zenn-editor/pull/435
- https://github.com/zenn-dev/zenn-editor/pull/431
=> release v0.1.141

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/matchers/isYoutubeUrl.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/utils/url-matcher.ts, packages/zenn-model/package.json
**changes**
- https://github.com/zenn-dev/zenn-editor/pull/445
=> release v0.1.143

packages/zenn-cli/src/server/__tests__/commands/index.test.ts, packages/zenn-cli/src/server/__tests__/lib/notify-update.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/blueprintue.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/codepen.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/codesandbox.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/common.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/figma.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/gist.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/github.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/jsfiddle.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/mermaid.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/slideshare.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/stackblitz.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/tweet.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/embed/youtube.test.ts, packages/zenn-markdown-html/__tests__/custom-syntax/messagebox.test.ts, packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts, packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts, packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts, packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts, packages/zenn-markdown-html/__tests__/matchers/isYoutubeUrl.test.ts
こちらのissueについて対応致しました。
Resolves #433
=> #433 テストのタイトルを日本語に統一する

.github/release-drafter.yml, .github/workflows/validate-pr.yml
=> labelのルールを修正しました

.github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish-latest.yml, .github/workflows/test.yml, package.json, pnpm-lock.yaml
pnpm を v8 にアップデートしました。
Resolves #443 
=> feat: pnpm を v8 にアップデート

.github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish-latest.yml, .github/workflows/test.yml, package.json, pnpm-lock.yaml
#456 とコンフリクトするので一旦 revert する。
Reverts zenn-dev/zenn-editor#457
=> Revert "feat: pnpm を v8 にアップデート"

.github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish-latest.yml, .github/workflows/test.yml, package.json, pnpm-lock.yaml
pnpm を v8 にアップデートしました。
Resolves #443 
=> chore: pnpm v8 にアップデートし、pnpm-lock を更新

packages/zenn-markdown-html/__tests__/toc.test.ts
=> TOCテストを日本語化

.github/workflows/publish-latest.yml
=> GitHub Actions の dispatch イベントに payload を追加

.github/workflows/publish-latest.yml, lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/toc.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
changes:
- [TOCテストを日本語化](https://github.com/zenn-dev/zenn-editor/commit/83e28135f071ad7e67faceede1d61f84b74fd93a)
- [import元を修正](https://github.com/zenn-dev/zenn-editor/commit/d6be6bfc7245dde5ebc7b570d39d196229a65bfa)
- [fix: dispatch イベントに payload を追加](https://github.com/zenn-dev/zenn-editor/commit/8cf7d2e219be85d7f139ee2daaa2140bdcc2feb1)
=> release v0.1.146

packages/zenn-cli/src/client/global.css
https://github.com/zenn-dev/zenn-editor/pull/456 への追記
=> ツールチップCSSのフォーク元を明記する

lerna.json, packages/zenn-cli/package.json, packages/zenn-cli/src/client/components/InsertAnchorButtonToHeadings.tsx, packages/zenn-cli/src/client/global.css, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/test.html, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
changes:
- #470 
- #472 
- #473
=> release v0.1.148

package.json
package.jsonからpackageManagerの項目を削除
ref: https://github.com/zenn-dev/zenn-editor/pull/475
合わせてドキュメントも修正
https://github.com/zenn-dev/zenn-docs-for-developers/pull/6
=> package.jsonからpackageManagerの項目を削除

packages/zenn-cli/articles/embed-examples.md, packages/zenn-markdown-html/__tests__/link.test.ts, packages/zenn-markdown-html/src/utils/url-matcher.ts
https://github.com/zenn-dev/zenn-community/issues/567
=> x.comの埋め込み対応

.github/workflows/publish-latest.yml
=> Publish workflowのnotifyをやめる

packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/src/_embed.scss, packages/zenn-content-css/src/_footnotes.scss, packages/zenn-content-css/src/_message.scss, packages/zenn-content-css/src/index.scss, packages/zenn-content-css/test.html
- 画像に枠線を追加
- Zenn本体のカラーパレットに色を寄せる
=> 画像に枠線を追加 & できるだけZenn本体のカラーパレットに色を寄せる

packages/zenn-content-css/src/_content.scss
=> 既存の記事への見た目の影響が想像より大きやったので差し戻し

packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/src/_message.scss, packages/zenn-content-css/src/index.scss
=> add: 角丸の定義を追加し、反映した

packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/test.html
ネストしたdetailsのスタイル崩れを修正しました
issue: https://github.com/zenn-dev/zenn-community/issues/588
=> ネストしたdetailsのスタイル崩れを修正

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/test.html, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
changes:
- https://github.com/zenn-dev/zenn-editor/pull/488
=> release v0.1.152

packages/zenn-markdown-html/__tests__/custom-syntax/embed/docswell.test.ts, packages/zenn-markdown-html/src/embed.ts
=> Docswellスライドの表示調整

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/custom-syntax/embed/docswell.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/embed.ts, packages/zenn-model/package.json
changes:
- https://github.com/zenn-dev/zenn-editor/pull/511
=> release 0.1.157

packages/zenn-cli/src/client/components/ErrorMessage.tsx
Twemoji SVGのリンク切れを修正
Resolves: https://github.com/zenn-dev/zenn-community/issues/680
=> TwemojiのCDNを修正

lerna.json, packages/zenn-cli/package.json, packages/zenn-cli/src/client/components/ErrorMessage.tsx, packages/zenn-cli/src/server/lib/helper.ts, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json, packages/zenn-model/src/index.ts, packages/zenn-model/src/types.ts, packages/zenn-model/src/utils.ts, pnpm-lock.yaml
=> release 0.1.159

.github/workflows/publish-canary.yml, .github/workflows/publish-latest.yml
setup-node actionの最新化
```
Run actions/setup-node@v2
Found in cache @ /opt/hostedtoolcache/node/18.20.8/x64
/home/runner/setup-pnpm/node_modules/.bin/pnpm store path
/home/runner/setup-pnpm/node_modules/.bin/store/v3
Error: Cache service responded with 422
```
=> feat: Node.jsセットアップアクションをv4に更新

packages/zenn-cli/src/client/global.css, packages/zenn-cli/src/client/index.html, packages/zenn-content-css/src/_embed.scss, packages/zenn-content-css/src/index.scss, packages/zenn-content-css/test.html
- https://github.com/zenn-dev/zenn-editor/pull/530#discussion_r2106345203 の対応
- styleタグをcssに移行
=> [リファクタリング] styleの修正

packages/zenn-content-css/src/_embed.scss
=> CSS判定の誤りを修正

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
=> fix: version 0.2.0

.gitignore, lerna.json, packages/zenn-cli/articles/100-example-markdown-guide.md, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/_content.scss, packages/zenn-content-css/test.html, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/__tests__/basic.test.ts, packages/zenn-markdown-html/package.json, packages/zenn-markdown-html/src/index.ts, packages/zenn-markdown-html/src/utils/md-image.ts, packages/zenn-model/package.json
=> release 0.2.0

lerna.json, packages/zenn-cli/package.json, packages/zenn-cli/src/server/__tests__/lib/helper.test.ts, packages/zenn-cli/src/server/__tests__/preview/app.test.ts, packages/zenn-cli/src/server/app.ts, packages/zenn-cli/src/server/lib/helper.ts, packages/zenn-content-css/package.json, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/__tests__/validator.test.ts, packages/zenn-model/package.json, packages/zenn-model/src/index.ts, packages/zenn-model/src/types.ts, packages/zenn-model/src/utils.ts
=> release 0.2.2

packages/zenn-content-css/src/index.scss
=> ダークテーマのリンクテキストの色を調整

lerna.json, packages/zenn-cli/package.json, packages/zenn-content-css/package.json, packages/zenn-content-css/src/index.scss, packages/zenn-embed-elements/package.json, packages/zenn-markdown-html/package.json, packages/zenn-model/package.json
=> release 0.2.3
