zenn-dev/zenn-editor

packages/zenn-cli/cli/preview/index.ts

短い間隔でファイルの保存処理を繰り返した場合MaxListenersExceededWarningがまだ発生するようなので、修正案を提出します。VSCodeだと保存のショートカットキー押しっぱなしで再現すると思います。

Fix MaxListenersExceededWarning when continuous saving

---

packages/zenn-cli/cli/init.ts

zennの独自記法を度々忘れることがあり、READMEにあると便利かなと思い提案してみます。
一方まだContribution Guide等ございませんでしたので、想定されている今後のzenn-initの方針と合わない場合はcloseいただければと思います

Suggestion: Append markdown guide

---

packages/zenn-cli/cli/constants.ts

`zenn new:article`が`zenn help`で2回表示されていたので、その修正になります。

Fix duplicate command of the usage

---

packages/zenn-cli/cli/init.ts

`zenn init`で生成される`README.md`の改行コードが抜けていたのを修正しました。

Fix generator of README.md

---

packages/zenn-cli/utils/nav-collections.ts

fix: escape emoji

---

packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/utils/md.ts
yarn.lock

https://github.com/steelydylan/markdown-it-imsize
markdown-it-imsizeの`autofill: true`オプションは使う必要があるか

chore: use another package to resize images on markdown

---

packages/zenn-markdown-html/src/@types/markdown-it-anchor.d.ts
packages/zenn-markdown-html/src/utils/md.ts
packages/zenn-markdown-html/tsconfig.json

markdownItAnchorがexport defaultされている関係上、普通にrequireで読み込んでしまうと、フロント側では`{ default: markdownItAnchor }`をrequireすることになってしまうため調整しました。
importで読み込むことでexport defaultでexportされたmoduleをtypescriptがフロントでもサーバーでも両方で動くコードにいい感じに変換してくれる

markdownItAnchorの読み込み方を調整

---

packages/zenn-markdown-html/src/utils/md-comment.ts
packages/zenn-markdown-html/src/utils/md.ts
packages/zenn-markdown-html/src/utils/option-md-custom-block.ts

`https://zennadev`や、`https://zenn.dev.example.com`等にもマッチしてしまっていたため修正
同上
`https://twitteracom/...`等にマッチしてしまっていたため修正

fix: escape regular expression characters

---

packages/zenn-cli/utils/validator.ts

`zenn-cli`の絵文字が有効かどうかを判別する関数の正規表現を、絵文字以外が含まれている場合にマッチしないように修正
`neko😺cat` => エラーが表示されない
`nekocat` => エラーが表示される
`😺😺` => エラーが表示されない
`😺` => エラーが表示されない
`neko😺cat` => エラーが表示される
`nekocat` => エラーが表示される
`😺😺` => エラーが表示される (絵文字は1文字だけ使えるため)
`😺` => エラーが表示されない

fix: change regular expression to only match emoji

---

packages/zenn-markdown-html/src/index.ts
packages/zenn-markdown-html/src/utils/md-line-number.ts
packages/zenn-markdown-html/src/utils/md-preview.ts

このPRでは、以下のように記述するとスクロール同期のために各HTMLに対応するテキストエリアの行番号が付与されるようになる。この後ももしかするとプレビューにだけ必要な機能を随時追加していくかもしれない。
```ts
import markdownToHtml, { enablePreview } from "zenn-markdown-html";
enablePreview();
...
markdownToHtml(html);
```

add line number as data attrs to each tags when preview mode

---

packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/@types/prism.d.ts
packages/zenn-markdown-html/src/utils/md-comment.ts
packages/zenn-markdown-html/src/utils/md.ts
packages/zenn-markdown-html/src/utils/prism.ts

markdown-it-prismでdynamicなrequireが使われていて、Next.jsとの相性が悪いため一部書き換えたものをzenn-markdown-htmlで内包するようにしました。

Chore: localのmarkdown-it-prismを使うように調整

---

packages/zenn-cli/cli/constants.ts
packages/zenn-cli/cli/new-article.ts
packages/zenn-cli/cli/new-book.ts
packages/zenn-cli/cli/preview/index.ts

`preview`, `new:article`, `new:book` のオプションとして `--help`, `-h` を追加し、これらが与えられた際はヘルプを表示するように切り替える処理を実装しました。
#17 
- 全オプションのヘルプを書くことも考えましたが、[使い方の記事](https://zenn.dev/zenn/articles/zenn-cli-guide) に未記載だったり、`--no-watch` のように非推奨にみえるオプションがあったので記事で紹介しているものに留めました。
- 文章は基本的に上記の記事内や元あるヘルプから取ってきていますが、これで良いかはわかりませんのでご確認頂ければと思います。
- helpの形式は [docopt](http://docopt.org/) を参考にしました。

Feature: コマンドへの `--help` optionの追加

---

packages/zenn-cli/cli/constants.ts
packages/zenn-cli/cli/new-article.ts
packages/zenn-cli/cli/new-book.ts
packages/zenn-cli/cli/preview/index.ts

引数をparseする際のErrorをerror codeで識別して `args` のオプションパース由来だった場合に弾いて決められたメッセージを表示するようにしました。
Close #17 .
- #55 では issueの半分の解決のみ、という一文を添えるべきでした。すみません。
- これ以上詳しい「どのコマンドでどの引数が間違っている云々」といった表示をしたい場合は #17 で @nnabeyang さんが言っている様に別のパーサを考えるか、何かしらその辺りをきちんとするしっかりめの処理を入れるかしないといけないかな、と思いました。 
- 文言はコマンドが無い時に合わせシンプルにしましたが, 「`-h` オプションで確認して下さい」程度の文言をつけてもいいかもしれないとも思いました。変更したほうが良ければReviewでRejectかCommentしてくださればと思います。

サブコマンドのオプションパースの例外処理

---

packages/zenn-cli/cli/new-article.ts
packages/zenn-cli/cli/new-book.ts
packages/zenn-cli/cli/preview/index.ts

Tried to run with `yarn start:cli`, I found compile errors below.
```
$ yarn start:cli new:article --help
yarn run v1.22.10
$ npm run build:bin && node bin/zenn.js new:article --help
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1606109443608-0.28473922880057456/node but npm is using /usr/bin/node 
itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> zenn-cli@0.1.57 build:bin /home/kyoh86/Projects/github.com/zenn-dev/zenn-editor/packages/zenn-cli
> rimraf dist/* && tsc --project tsconfig.cli.json
cli/new-article.ts:48:26 - error TS2345: Argument of type 'string[] | undefined' is not assignable to parameter of type 'string[]'.
Type 'undefined' is not assignable to type 'string[]'.
48   const args = …
```

fix parseArgs parameter type

---

packages/zenn-cli/cli/constants.ts

`zenn preview --help`に`--open`の項目が抜けていたので追加しました。

fix: help text

---

packages/zenn-cli/cli/constants.ts

`zenn help` を叩いてみたら Powershell のコンソールで変な文字が表示されたのでソース見てみようと思って開いたら空白文字を見つけた、というだけです（深い意味はありません）。
ちなみに、変な文字になってたのは絵文字でした。詳しく調べてないですが Zenn の問題ではないと思います。

不要なスペースを除去

---

packages/zenn-cli/cli/constants.ts

詳細の文字が絵文字と被ってしまっていたため修正しました。
私の手元のvscodeではこのようになってしまっていますが
ターミナルでは
iTermでは
となっており、vscodeでの場合のみ被ってしまっています。
大した問題ではないですが気になったのでPRを出しました。

fixed overlapping of text

---

packages/zenn-cli/cli/new-article.ts
packages/zenn-cli/cli/new-book.ts

`npx zenn new:article` でファイルをつくると以下のように絵文字ととファイル名の間にスペースがない状態で出力される。
VSCodeなどのTerminalで出力したときにファイル名をクリックすれば該当のファイルが開く機能があるが、この絵文字とファイル名がつながっていることにより以下のように直接ファイルが開けず面倒になっている。
1. 絵文字とファイル名にスペースを入れる
2. 絵文字を消す
どちらでもいいが今回は1を採用したPRを作成した。

新しいファイルを作ったときのcliの出力で絵文字とファイル名の間にスペースを入れる

---

packages/zenn-cli/cli/constants.ts
packages/zenn-cli/cli/index.ts

fix #79 です。zennコマンド自体の引数の`help`を`--help, -h`に変更します。
他のコマンドと合わせるために変更にしましたが、問題があれば元のhelpも戻します。

feat: change the "help" argument of zenn itself to have a hyphen

---

packages/zenn-cli/articles/code-fence.md
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/utils/md-prism.ts
packages/zenn-markdown-html/src/utils/prism-plugins/diff-highlight.ts
yarn.lock

Resolves #86 .
Use the similar way with `diff-highlight` plugin of `markdown-it-prism`.
https://zenn.dev/kkiyama117/scraps/05094a5e9f8db8
~~may conflict with #103.~~ this change do not cause confliction unless you treat prism through markdown-it instance.

Language highlight with diff on markdown in articles and books

---

packages/zenn-cli/cli/constants.ts
packages/zenn-cli/cli/index.ts
packages/zenn-cli/cli/list-articles.ts
packages/zenn-cli/cli/list-books.ts

list:booksが動かずrevertに至ってしまった #125 の焼き直しになります。
last commit: 1f474ab をもってlist:booksも正しい挙動を得られました
```console
$ yarn workspace zenn-cli run start:cli list:books
yarn workspace v1.22.10
yarn run v1.22.10
$ npm run build:bin && node bin/zenn.js list:books
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1614785099705-0.4860827309988136/node but npm is using /usr/bin/node i
tself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> zenn-cli@0.1.75 build:bin /home/kyoh86/Projects/github.com/zenn-dev/zenn-editor/packages/zenn-cli
> rimraf dist/* && tsc --project tsconfig.cli.json
by-chapter-filename     ファイル名からデプロイ
new-chapter-structures  新しい構造のチャプター
slug-of-example-book    本のタイトルをここに
Done in 5.37s.
Done in 5.60s.
``` …

Revival "記事や本のリストを表示するコマンドの追加"

---

packages/zenn-cli/components/ChapterHeader.tsx

`1-2-3-foo.md`のようなslugの場合、slugが`2-3-foo`となってしまうようです。
`.`が正規表現として動くため、`1-`が消えているようでした

fix: slugのドット記号がエスケープされておらず、意図しない省略がされる問題の修正

---

packages/zenn-cli/components/MainContainer.tsx
packages/zenn-cli/public/chevron.svg
packages/zenn-cli/styles/components/_main-container.scss

https://github.com/zenn-dev/zenn-editor/issues/141
1画面で執筆している場合には Zenn CLI のプレビューでサイドバーを非表示にできると執筆体験が向上すると思いましたのでPRさせていただきました。
なるべく既存コードを変更しない様に表示/非表示のトグルボタンを設置しております。
別のPRで下記の様に記載されていましたが、問題ない様でしたらご確認いただければ幸いです。
> zenn-cliを一度作り直そうと思っておりまして、新しい機能の追加などはストップしています。
> zenn-dev/zenn-community#262
> 
> また、しばらくは
> 
> UIの改善
> 画像アップロードの仕組みの改善
> などの多くのユーザーにとって重要となるポイントに注力しようと思っています。

chore: Added sidebar minimize button to Zenn CLI preview

---

packages/zenn-embed-elements/src/classes/katex.ts

- 現在のversion`0.12.0`であると`align`という数式命令が動作しなくて不便である
- <img width="567" alt="image" src="https://user-images.githubusercontent.com/612043/120899480-ea059700-c66a-11eb-8e0c-3307405bbe30.png">
- 下記のSupported Functionsに記載があるため、現在の最新版では使えると考えてバージョンアップした
- https://katex.org/docs/supported.html
- Zenn CLI上での動作確認を行いたかったが、TypeScriptなどの知識がなくてできなかった…… 🙇 
- エラーとなったLaTeX
```latex
\def\bra#1{\mathinner{\left\langle{#1}\right|}}
\def\ket#1{\mathinner{\left|{#1}\right\rangle}}
\def\braket#1#2{\mathinner{\left\langle{#1}\middle|#2\right\rangle}}
\begin{align}
\left\{
\begin{array}{l}
\ket{\psi_{0,0}} \equiv \ket{0} \\
\ket{\psi_{0,1}} \equiv \ket{1} \\
\ket{\psi_{1,0}} \equiv \ket{+} \\
\ket{\psi_{1,1}} \equiv \ket{-}
\end{array}
\right.& \\
&\text{where}\; \ket{\pm} \equiv \frac{1}{\sqrt{2}}\left(\ket{0} …
```

Update KaTeX version

---

.github/workflows/publish-canary.yml
.github/workflows/publish-latest.yml
packages/zenn-embed-elements/src/classes/katex.ts

ref: https://github.com/zenn-dev/zenn-community/issues/304

KaTexのバージョンを一旦v0.12.0に固定

---

packages/zenn-cli/src/client/components/Routes.tsx
packages/zenn-cli/src/client/components/Sidebar.tsx
packages/zenn-cli/src/client/components/guide/index.tsx
packages/zenn-cli/src/client/components/home/index.tsx
packages/zenn-cli/src/server/preview/api/cli-guide.ts
packages/zenn-cli/src/server/preview/app.ts

- ガイドページのURLを`/guide`から`/guide/:slug`に変更し、`:slug`にzenn.dev上のドキュメントのslugを指定するように
- これまでのCLIドキュメント`zenn-cli-guide`に加えて、`deploy-github-images`のドキュメントをサイドバーに追加

ドキュメントに画像の管理についての説明を追加

---

packages/zenn-cli/articles/example-images.md
packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
packages/zenn-cli/src/client/lib/validator.ts
packages/zenn-cli/src/server/lib/helper.ts

zenn previewにて、画像ファイルの存在確認とファイルサイズの検証を追加しました。

画像ファイルの存在確認とファイルサイズの検証を追加

---

packages/zenn-markdown-html/__tests__/basic.test.ts
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/@types/markdown-it-anchor.d.ts
packages/zenn-markdown-html/src/index.ts
yarn.lock

bump markdown-it-anchor

---

packages/zenn-cli/package.json
yarn.lock

- ref: https://github.com/zenn-dev/zenn-editor/issues/230
あくまでも暫定対処。移行を検討

`color`をv1.4.0に固定

---

packages/zenn-cli/articles/math.md
packages/zenn-cli/articles/mermaid.md
packages/zenn-embed-elements/src/classes/katex.ts
packages/zenn-embed-elements/src/classes/mermaid.ts
packages/zenn-markdown-html/package.json
yarn.lock

- ref: https://github.com/zenn-dev/zenn-community/issues/366
- ref: https://github.com/zenn-dev/zenn-community/issues/361

Chrome 97から`<details>`内でKatexやmermaidがレンダリングされない問題の解消

---

packages/zenn-embed-elements/src/classes/mermaid.ts

- Safariにおいて`<details>`タグ内のmermaid.jsのレンダリングが正常に行われない問題を解消

fix: mermaid.jsがsafariのdetails内でレンダリングされない問題

---

packages/zenn-cli/articles/math.md
packages/zenn-markdown-html/__tests__/dollar.test.ts
packages/zenn-markdown-html/src/utils/md-katex.ts

スキップしたい範囲が意図せず広範囲に及び、本来数式判定するところまで波及していたためスキップ判定を変えました。ただ、やっている事自体は前の正規表現と大きく変わっていません。
- 前：URLに'$'を含むアンカーがある場合はスキップする
- 後：URLに'$'以外の文字列でアンカーが構成される場合はスキップする
「`$`を含むアンカー」という判定になっていたため、これを見つけた場合にスキップが優先されてしまい、 `$数式$リンクはこちら[example](https://example.com/hi),ref:$(2)$` という行は  `数式$リンクはこちら[example](https://example.com/hi),ref:$(2)` ここまでが条件を満たすURL判定となってしまっていた。
ref: https://github.com/zenn-dev/zenn-community/issues/368
検証のあと: https://integration.zenn.studio/waddy/scraps/221fc8ca5ff035#comment-7219866668fd9c

KaTeXの正規表現修正

---

packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/prism-plugins/prism-diff-highlight.ts
packages/zenn-markdown-html/src/utils/highlight.ts
yarn.lock

tsx などの html タグを使用するフォーマットと diff フォーマットを使用すると余分な一行が追加されてしまうバグを修正しました。
**修正内容**
- `@steelydylan/prism-diff-highlight` を node_modules から削除
- `@steelydylan/prism-diff-highlight` の内容を `prism-plugins/prism-diff-highlight.ts`  に移動
- `prism-diff-highlight.ts` 内の正規表現を修正
Resolves https://github.com/zenn-dev/zenn-community/issues/255

fix: tsx の差分フォーマットで余分な一行が表示されてしまうバグを修正

---

packages/zenn-embed-components/package.json
packages/zenn-embed-components/tsconfig.build.json
packages/zenn-embed-components/tsconfig.json

`zenn-embed-components` 内に新しく `tsconfig.build.json` を作り、ビルド時はそのファイルを参照するように設定しました。
**理由**
ビルドする際、Storybook のファイルが含まれないように `excludes` に `**/*.stories.tsx` を設定していましたが、それだとStorybookファイル内の型システムが上手く動作しなかったため、デフォルトの `tsconfig.json` では `excludes` は設定せずに、ビルド時のみの設定するようにしました。
これにより、Storybook内でも上手く型システムが動作するはずです。

fix: `zenn-embed-components` のビルド設定を修正

---

packages/zenn-cli/articles/example-tweets.md
packages/zenn-markdown-html/src/utils/url-matcher.ts

TwitterのURLに`&`が含まれていると、Twitterカードが表示されないバグを修正しました。
**修正内容**
- Twitterの正規表現を修正
- TwitterのサンプルMarkdownに該当のURLを追加

fix: twitterのURLに'&'が含まれていると正規表現にマッチしないバグを修正

---

packages/zenn-cli/package.json
packages/zenn-markdown-html/__tests__/basic.test.ts
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/__tests__/dollar.test.ts
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/src/index.ts
yarn.lock

Next.jsでのブラウザバック時のスクロール位置の保持が厳しいため、リンクは別タブで開く形に変更

markdown内のリンクを別タブで開くように

---

packages/zenn-content-css/src/_message.scss

- ref: https://github.com/zenn-dev/zenn-community/issues/381
- 以下のようなスタイルに変更

メッセージ記法のアイコンを上下中央から上揃えへと変更

---

packages/zenn-content-css/src/_message.scss
packages/zenn-content-css/test.html
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/src/utils/md-container.ts

`:::message` および `:::message alert` 記法へのセマンティクスの拡充
- アイコンを `:::before` から `<svg>` に
- `<svg>` に `aria-label` で `message` or `alert` を付与
- CSS を修正
- テストの修正
あまりコーディングルール的なものがわからなかったので、リファクタリングは適宜お願いします。
CSS は基本は同じように移植してますが、検証パターンがわからなかったので確認していただけると。
Resolves #273

#273 `:::message` 記法のセマンティクス拡充

---

packages/zenn-content-css/src/_message.scss
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/src/utils/md-container.ts

`:::message`記法のアイコンの位置調整のために`absolute`を使っていたが`flex`を使う形に変更。

:::message をflexを使う形に修正

---

packages/zenn-content-css/src/_message.scss

````
:::message
```
めっちゃ長いコード
```
:::
````
上記のように `message` 内のコードブロックに長い文字列があると、コードブロック要素がはみ出してしまうバグを修正しました。
参照：https://github.com/zenn-dev/zenn-community/issues/385

fix: message内のコードブロックがはみ出してしまうバグを修正

---

packages/zenn-content-css/src/_embed.scss
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/__tests__/mermaid.test.ts
packages/zenn-markdown-html/src/utils/helper.ts

埋め込まれる link-card の高さを固定にするように修正

fix: link-cardの場合はiframeの高さを固定にするように修正

---

packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
packages/zenn-markdown-html/src/utils/helper.ts

リポジトリ名にドットが入っているとGithubファイルのリンクとして認識されないバグを修正しました。
それと、簡素なモノではありますがテストを書きました。

fix: リポジトリ名にドットが入っているリンクがGithubの埋め込みとして表示されないバグを修正

---

packages/zenn-markdown-html/src/utils/helper.ts

リポジトリ名に`_`が含まれていてもGitHub埋め込みとして正しく表示させるように修正しました。

fix: リポジトリ名に`_`が含まれているとGitHub埋め込みが機能しなくなるバグを修正

---

packages/zenn-markdown-html/src/utils/helper.ts

GitHubリンクに長いリポジトリ名があると、埋め込みが機能しないバグを修正
Resolves #295 

fix: GitHubリンクの正規表現を修正

---

packages/zenn-cli/articles/code-fence.md
packages/zenn-cli/articles/example.md
packages/zenn-cli/articles/exampleexample.md
packages/zenn-cli/articles/math.md
packages/zenn-cli/articles/mermaid.md
packages/zenn-cli/articles/xss.md
packages/zenn-cli/package.json
packages/zenn-cli/src/client/components/ValidationErrors.tsx
packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
packages/zenn-cli/src/client/lib/validator.ts
packages/zenn-cli/src/common/types.ts
packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md
packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
packages/zenn-cli/src/server/lib/articles.ts
yarn.lock

articleのpreviewにて、frontmatterに`published_at`が指定されている場合、ヘッダーに情報を表示します。
関連するIssue: https://github.com/zenn-dev/zenn-community/issues/183

articleのpreviewにてpublished_atをサポート

---

packages/zenn-cli/webpack.server.js

`zenn-cli`のビルドファイルに package.json が含まれてしまい、アップデート通知が正しく動作しない問題を修正しました。
修正では、[webpack の externals](https://webpack.js.org/configuration/externals/) を使用して、package.json をビルドファイルに含めないようにしています。

feat: zenn-cliのビルドファイルにpackage.jsonを含めないように修正

---

packages/zenn-cli/articles/exampleexample.md
packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
packages/zenn-cli/src/client/index.html
packages/zenn-cli/src/client/lib/validator.ts
packages/zenn-cli/src/common/types.ts

Publication対応の一環です。
表示とバリデーションを追加したのみで、デプロイしてもただちにサーバー側で処理されるわけではありません。
refs: https://github.com/zenn-dev/zenn-community/issues/275

front matter で publication_name を受け付けるように修正

---

packages/zenn-cli/package.json
packages/zenn-cli/webpack.server.js

node v14 より前のバージョンを使用していると、`zenn preview` が実行時エラーになってしまうバグを修正しました。
Resolves #308 
- zenn-cli がサポートする node のバージョンを `>=10.13.0` から `>=14.0.0` に修正しました

zenn-cliが実行時エラーになるバグを修正

---

packages/zenn-cli/package.json
packages/zenn-cli/src/client/lib/validator.ts
yarn.lock

Resolves #318
- zenn-cli の依存関係であり、絵文字のバリデーションに使っている [emoji-regex](https://github.com/mathiasbynens/emoji-regex) のバージョンを v9.2.2 から v10.1.0 に更新しました
- emoji-regex の更新に伴い、`initEmojiRegex`のインポート方法を修正しました（[参考](https://github.com/mathiasbynens/emoji-regex/blob/v10.1.0/index.d.ts)）
- 更新後はエラーが表示されなくなります（🫠 [1FAE0](https://unicode.org/emoji/charts-14.0/emoji-released.html#1fae0)）
- emoji-regex は v10 から [emoji-test-regex-pattern](https://github.com/mathiasbynens/emoji-test-regex-pattern) というパッケージで絵文字の管理を行うようになりました（[参考](https://github.com/mathiasbynens/emoji-regex/commit/30c11fcf654f7fbefce1958e9df9889ee1b5edcf)）
- emoji-test-regex-pattern は v1.4.0 より Emoji 14.0 に対応しています（[参考](https://github.com/mathiasbynens/emoji-test-regex-pattern/commit/0dbbe2aa9f0a3dbe5a2b0b862ad6491adad63d7a)）
- emoji-regex …

fix: error message when specifying Emoji 14

---

packages/zenn-cli/articles/embed-examples.md
packages/zenn-markdown-html/src/utils/url-matcher.ts

CodeSandBoxの埋め込みURLに`,`を含められるように修正しました。
https://github.com/zenn-dev/zenn-community/issues/422

fix: CodeSandBoxの埋め込みURLに`,`を含められるように修正

---

packages/zenn-content-css/src/_footnotes.scss

- https://github.com/zenn-dev/zenn-community/issues/425
- 対応した脚注が分かりやすいようにハイライトする

アクティブな脚注がわかりやすいようにハイライト

---

packages/zenn-cli/package.json
packages/zenn-cli/src/client/components/Sidebar.tsx
packages/zenn-cli/src/client/components/ValidationErrors.tsx
packages/zenn-cli/src/client/components/books/show.tsx
packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
packages/zenn-cli/src/client/components/sidebar/Directory.tsx
packages/zenn-cli/src/client/components/sidebar/ListItemInner.tsx
packages/zenn-cli/src/client/components/sidebar/Settings.tsx
packages/zenn-cli/src/client/lib/validator.ts
yarn.lock

refs: https://github.com/zenn-dev/zenn-editor/issues/337
material-ui はコンポーネントもスタイリングでも使っていません。iconのために利用していましたが、このiconも [react-icons](https://react-icons.github.io/react-icons/icons?name=md) に置き換えられることがわかったため、matreial-ui をプロジェクトから外します。

material-icons のために導入していた material-ui を廃止し、かわりに react-icons/md を導入した

---

packages/zenn-content-css/src/_content.scss

タスクリストのサブリスト内でリストマーカーが表示されない問題を修正しました。
ref: https://github.com/zenn-dev/zenn-community/issues/428

fix: タスクリストのサブリストのリストマーカーを表示するように修正

---

packages/zenn-markdown-html/README.md
packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/index.ts
packages/zenn-markdown-html/src/markdown-to-simple-html.ts
packages/zenn-markdown-html/src/utils/md-link-attributes.ts
yarn.lock

packages/zenn-markdown-html に markdownToSimpleHtml を追加

markdownToSimpleHtmlを追加

---

packages/zenn-cli/articles/embed-examples.md
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/src/utils/md-custom-block.ts
packages/zenn-markdown-html/src/utils/url-matcher.ts

refs:
https://github.com/zenn-dev/zenn-community/issues/433
https://github.com/zenn-dev/zenn-community/issues/410
このブランチをチェックアウト
```
yarn build
cd packages/zenn-cli
yarn dev
```

figma と blueprintue の埋め込みを追加した

---

packages/zenn-cli/articles/link-card.md
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts

`<details />` 内でも Linkify な埋め込み要素を表示できるように修正しました。
Resolves #353 

feat: details内でもLinkifyの埋め込みをできるようにした

---

packages/zenn-content-css/src/_embed.scss
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/src/utils/md-custom-block.ts

- スマホで見たときに縦幅が大きすぎると、画面スクロール自体の体験を損ねる可能性があると指摘
- figmaの背景が白いことがあるのでiframe境界がわかりやすいよう修正

fix: figmaとblueprintue の埋め込み枠を16:9にした

---

packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/src/utils/url-matcher.ts

blueprintのURLを判定する正規表現で`_`を許容するように修正しました。
Resolves https://github.com/zenn-dev/zenn-community/issues/410#issuecomment-1245290686

fix: URLに`_`が含まれているとblueprintが埋め込めないバグを修正

---

packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
packages/zenn-markdown-html/src/utils/embed-helper.ts
packages/zenn-markdown-html/src/utils/helper.ts
packages/zenn-markdown-html/src/utils/md-custom-block.ts
packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
packages/zenn-markdown-html/src/utils/url-matcher.ts

LinkCard 以外の埋め込みURL文字列に文字数制限をかけるように修正しました。
現在は 300 文字以下に制限しています。

feat: LinkCard以外の埋め込みURL文字数制限をかけるように修正

---

packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
packages/zenn-cli/src/server/commands/new-article.ts
packages/zenn-cli/src/server/lib/messages.ts

記事作成後に都度 publication_name を埋めるのは面倒なので、コマンドオプションで指定できるようにしました。
(Issueでの議論を経ていませんが、小さな変更なので先にPRも立てています。)
Resolves #372

new:article に --publication-name オプションを追加

---

packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
packages/zenn-cli/src/client/lib/validator.ts

Safari でプレビューを確認すると、`published_at` が正しく指定されているにもかかわらず、エラーが発生してしまうバグを修正しました。
ref: https://github.com/zenn-dev/zenn-community/issues/441

fix: safari で `published_at` 指定時にエラーが発生してしまうバグを修正

---

packages/zenn-cli/articles/exampleexample.md
packages/zenn-content-css/src/_content.scss
packages/zenn-content-css/src/_message.scss

:::message記法内でdetails/summaryやlink-cardが使われたときに見た目がやや崩れる問題を解消

---

.github/workflows/policy-comment.yml
packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
packages/zenn-cli/src/server/commands/new-article.ts

https://github.com/zenn-dev/zenn-editor/pull/373 で記事生成時のオプションに `--publication-name` を追加したのですが、生成される front matter 項目を `publication-name` にしてしまっており正しく認識されていませんでした。
正しくは `publication_name` だったのでこちらに修正しました。
元PRの不備ですみませんが fix PR として取り込みをお願いします:pray:

new:articlesの--publication-nameオプションで生成されるfront matter名が誤っていたため修正

---

packages/zenn-cli/articles/embed-examples.md
packages/zenn-cli/articles/exampleexample.md
packages/zenn-cli/articles/link-card.md
packages/zenn-cli/src/server/commands/new-article.ts
packages/zenn-content-css/test.html
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/src/utils/embed-helper.ts

YouTubeの埋め込みで初回アクセス時に「この動画は再生できません」と表示される
原因となっているループ再生をやめて、[プライバシー強化モード](https://support.google.com/youtube/answer/171780?hl=ja#zippy=%2C%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E5%BC%B7%E5%8C%96%E3%83%A2%E3%83%BC%E3%83%89%E3%82%92%E6%9C%89%E5%8A%B9%E3%81%AB%E3%81%99%E3%82%8B)に変更する
ループ再生にした経緯: https://github.com/zenn-dev/zenn-community/issues/143 
Resolves: https://github.com/zenn-dev/zenn-community/issues/439
関連: #352

YouTubeの埋め込みをプライバシー強化モードに変更

---

packages/zenn-content-css/src/_message.scss
packages/zenn-content-css/test.html
packages/zenn-markdown-html/__tests__/custom.test.ts
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/src/utils/md-container.ts

将来的にサニタイズ方式でHTMLタグの使用を許可するため、markdownから変換したHTMLに含まれるsvgタグを安全なタグに変更します。
before
after

変換したHTMLに含まれるsvgタグを安全なタグに変更

---

packages/zenn-content-css/src/_message.scss
packages/zenn-markdown-html/src/sanitizer.ts

#395 の続きです。既存データのアップデートが完了したため、サニタイズリストからsvgタグの削除と、svgタグに設定されていたcssを削除します。

サニタイズリストからsvgを削除

---

packages/zenn-content-css/src/_content.scss

ページ内に複数の h1 があるのは避けるのがベストプラクティス( [参考](https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements#1_%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AB%E8%A4%87%E6%95%B0%E3%81%AE_h1_%E8%A6%81%E7%B4%A0%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AF%E9%81%BF%E3%81%91%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84) )ですが、現状の zenn のスタイルは h1 から使い始めるようなスタイルになっているため、ページ内に複数の h1 が表示されやすくなります。そのため、 `<h2 />` にも下線をつけるように修正しました。

fix: h2 にも下線をつけるように修正

---

packages/zenn-cli/package.json
packages/zenn-cli/src/server/lib/server.ts

- ビルド後のファイルでのみ websocket が実行エラーを吐いてしまうバグを修正

fix: zenn-cli のコマンド実行時に websocket で実行時エラーが発生してしまうバグを修正

---

packages/zenn-content-css/src/_prism.scss

以下の画像のように `label_2` の行のインデントが表示されない問題を修正しました。
https://github.com/zenn-dev/zenn-editor/issues/130 の問題を修正するためのコードが影響していましたが、この Issue の問題は既に https://github.com/zenn-dev/zenn-editor/pull/248 で解決済みなため、削除しても問題ないと判断しました。

fix: diff のコードブロックでインデントが崩れてしまう問題を修正

---

packages/zenn-markdown-html/__tests__/matchers/isYoutubeUrl.test.ts
packages/zenn-markdown-html/src/utils/url-matcher.ts

Youtube の動画URL以外のURLが動画URLとして判定されてしまうバグを修正しました。
関連 https://github.com/zenn-dev/zenn-community/issues/516

fix: youtubeのplaylistのURLが間違ってyoutubeの動画URLとして判定されてしまうバグを修正

---

packages/zenn-cli/src/server/__tests__/commands/index.test.ts
packages/zenn-cli/src/server/__tests__/lib/notify-update.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/blueprintue.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/codepen.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/codesandbox.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/common.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/figma.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/gist.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/github.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/jsfiddle.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/mermaid.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/slideshare.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/stackblitz.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/tweet.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/embed/youtube.test.ts
packages/zenn-markdown-html/__tests__/custom-syntax/messagebox.test.ts
packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts
packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
packages/zenn-markdown-html/__tests__/matchers/isYoutubeUrl.test.ts

Reverts zenn-dev/zenn-editor#447
ISSUEに対しての修正が逆のため、申し訳ありませんがrevertします。

Revert "#433 テストのタイトルを日本語に統一する"

---

packages/zenn-embed-elements/src/classes/katex.ts
packages/zenn-embed-elements/tsconfig.json

他の処理との兼ね合いで、バージョンを指定すると管理が難しくなってしまうため、バージョンを指定せずに CDN から読み込む形に修正しました。

fix: katex のバージョンを指定せずに CDN から読み込むように修正

---

packages/zenn-cli/src/client/__tests__/lib/helper.test.ts
packages/zenn-cli/src/common/__tests__/helper.test.ts
packages/zenn-cli/src/server/__tests__/commands/help.test.ts
packages/zenn-cli/src/server/__tests__/commands/init.test.ts
packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
packages/zenn-cli/src/server/__tests__/commands/new-book.test.ts
packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
packages/zenn-cli/src/server/__tests__/commands/version.test.ts
packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
packages/zenn-cli/src/server/__tests__/lib/log.test.ts
packages/zenn-markdown-html/__tests__/basic.test.ts
packages/zenn-markdown-html/__tests__/br.test.ts
packages/zenn-markdown-html/__tests__/dollar.test.ts
packages/zenn-markdown-html/__tests__/highlight.test.ts
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/__tests__/xss.test.ts
packages/zenn-model/__tests__/validator.test.ts

実装してあるテストのタイトルを日本語に統一しました。
Resolves #433

refactor: テストのタイトルを日本語に統一

---

packages/zenn-content-css/src/_content.scss
packages/zenn-content-css/test.html

以下のように画像をリンクにして画像が画面幅より小さい場合、リンクの範囲が画面幅いっぱいになってしまう問題を修正。
```
[![altテキスト](https://画像のURL =250x)](https://zenn.dev)
```

リンクの中に画像があるとき、リンク範囲を画像の大きさに合わせる

---

lerna.json
packages/zenn-cli/articles/embed-examples.md
packages/zenn-cli/package.json
packages/zenn-content-css/package.json
packages/zenn-embed-elements/package.json
packages/zenn-markdown-html/__tests__/link.test.ts
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/utils/url-matcher.ts
packages/zenn-model/package.json

release v0.1.150

---

packages/zenn-markdown-html/__tests__/matchers/isCodesandboxUrl.test.ts
packages/zenn-markdown-html/src/utils/url-matcher.ts

CodeSandboxのembed URL に `+` を許可するように修正。
issue: #490

Codesandbox URL に `+` を許容する

---

lerna.json
packages/zenn-cli/package.json
packages/zenn-content-css/package.json
packages/zenn-embed-elements/package.json
packages/zenn-markdown-html/__tests__/matchers/isCodesandboxUrl.test.ts
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/utils/url-matcher.ts
packages/zenn-model/package.json

changes: 
- https://github.com/zenn-dev/zenn-editor/pull/491

release v0.1.153

---

packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
packages/zenn-cli/src/server/commands/init.ts
packages/zenn-cli/src/server/lib/helper.ts

以下のIssueに関連して、プロジェクトフォルダ内に存在するLockfileから使用しているパッケージマネージャー(エグゼキューター)を推測し、`zenn init`を実行後に表示されるヘルプコマンドについて、`npx`, `yarn`等を使用することを明示的に表記するように変更しました。
Resolves https://github.com/zenn-dev/zenn-editor/issues/344

feat: `zenn init`で表示されるヘルプコマンドにパッケージマネージャーを使用することを明示的に追加

---

packages/zenn-cli/articles/304-example-embed-katex.md
packages/zenn-content-css/src/_embed.scss

一部のブラウザで、数式番号を振った場合にスクロールバーが表示されてしまう問題を修正しました。
副作用として、インライン要素も2pxのpaddingが追加されるため、文中に2px分の空白が生じますが、許容できる判断しています。
issue: https://github.com/zenn-dev/zenn-community/issues/608

不要なスクロールバーが表示されないようにネガティブマージンを相殺する

---

.vscode/settings.json

- `source.fixAll.eslint` フィールドで boolean が deprecated になったので、true に相当する explicit に修正しました。

fix: VSCode ESLint 設定の Deprecated 対応

---

packages/zenn-cli/articles/305-example-embed-others.md
packages/zenn-content-css/src/_embed.scss
packages/zenn-markdown-html/__tests__/custom-syntax/embed/docswell.test.ts
packages/zenn-markdown-html/__tests__/matchers/isDocswellUrl.test.ts
packages/zenn-markdown-html/src/embed.ts
packages/zenn-markdown-html/src/utils/url-matcher.ts

参考: https://github.com/zenn-dev/zenn-editor/pull/322
Resolves https://github.com/zenn-dev/zenn-editor/issues/321

ドクセル埋め込み対応

---

packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
packages/zenn-markdown-html/src/index.ts

markdown変換で、メールアドレスを自動で検知して `mailto:` のリンクに変換しているが、Zennオリジナルのリンクカード化が意図せず動いてしまいうまく機能していない。具体的には以下のように変換されてしまう。
```
ec2-user@33.80.180.159
```
↓
```
URLが不正です
```
そもそもメールアドレスを検知して `<a mailto="ec2-user@35.79.180.159">ec2-user@35.79.180.159</a>` のように変換する処理が不要と考えたため、本機能を無効にします。

fuzzyEmail を無効にする

---

lerna.json
packages/zenn-cli/package.json
packages/zenn-content-css/package.json
packages/zenn-embed-elements/package.json
packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/index.ts
packages/zenn-model/package.json

release 0.1.158

---

packages/zenn-cli/src/server/lib/helper.ts
packages/zenn-model/package.json
packages/zenn-model/src/index.ts
packages/zenn-model/src/types.ts
packages/zenn-model/src/utils.ts
pnpm-lock.yaml

画像の参照エラー等を、既存のエラーと同じ場所に出してあげることで UX を改善する。
内部的には `zenn-cli/server` で出力するタグに専用のクラスを追加し、それを `zenn-model` から全文検索で検出している。
将来的にクラスを増やすことで別メッセージを出力させるようにすることも可能。
2つのパッケージに同じ単語を入れなければならない暗黙的なルールができてしまう所は要検討か。
Resolves https://github.com/zenn-dev/zenn-community/issues/681

feat: サーバが出した画像エラーを目立たせるようにする

---

packages/zenn-cli/src/client/index.html
packages/zenn-content-css/src/_content.scss
packages/zenn-content-css/src/_embed.scss
packages/zenn-content-css/src/_footnotes.scss
packages/zenn-content-css/src/_message.scss
packages/zenn-content-css/src/index.scss
packages/zenn-content-css/test.html

zenn-content-css に dark theme を追加して theme を切り替え可能にしました。
これは zenn.dev の改修に伴うもので、zenn.dev 以外での theme の提供はまだ考慮していません。
- ルートで pnpm run build
- packages/zenn-cli で pnpm run dev
- http://localhost:3333/articles/100-example-markdown-guide などを見る
- 通常の theme で違和感がないか
- 開発者コンソールから html タグの data-theme を dark-blue に書き換え
- dark theme で違和感がないか

zenn-content-css に dark theme を追加

---

packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
packages/zenn-markdown-html/src/embed.ts

#527
この記法でSpeakerDeckで表示したいスライドの番号を指定し、表示します。
```
@[speakerdeck](f005615e42d84c9b8bdb7fd722cbbbd9?slide=2)
```
- 付録1参照
- 正規表現でチェック(コメント参照)
- 付録1参照
`packages/zenn-cli/articles/305-example-embed-others.md`
```diff
@[speakerdeck](f8653c8c6ffc4f54bb4683daa8c1a284)
@[speakerdeck](4f926da9cb4cd0001f00a1ff)
+@[speakerdeck](f8653c8c6ffc4f54bb4683daa8c1a284?slide=20)
+
+@[speakerdeck](4f926da9cb4cd0001f00a1ff?slide=15)
```
|pc|モバイル|
|---|---|
|![CleanShot 2025-04-28 at 13 48 12@2x](https://github.com/user-attachments/assets/85baf025-4ca4-4b75-bf71-91edf81a2686)|![IMG_25203241E73C-1](https://github.com/user-attachments/assets/99ae82eb-a …

feat: SpeakerDeck埋め込み要素にスライド番号のサポートを追加

---

lerna.json
packages/zenn-cli/package.json
packages/zenn-cli/src/client/index.html
packages/zenn-content-css/package.json
packages/zenn-content-css/src/_content.scss
packages/zenn-content-css/src/_embed.scss
packages/zenn-content-css/src/_footnotes.scss
packages/zenn-content-css/src/_message.scss
packages/zenn-content-css/src/index.scss
packages/zenn-content-css/test.html
packages/zenn-embed-elements/package.json
packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
packages/zenn-markdown-html/package.json
packages/zenn-markdown-html/src/embed.ts
packages/zenn-model/package.json

[#528 feat: SpeakerDeck埋め込み要素にスライド番号のサポートを追加](https://github.com/zenn-dev/zenn-editor/pull/528)
[#529 zenn-content-css に dark theme を追加 ](https://github.com/zenn-dev/zenn-editor/pull/529)
親windowのthemeによって、iframe内のcolor-schemeを指定する by cm-igarashi-ryosuke · Pull Request #530 · zenn-dev/zenn-editor https://github.com/zenn-dev/zenn-editor/pull/530

release 0.1.160

---

packages/zenn-model/__tests__/validator.test.ts
packages/zenn-model/src/index.ts
packages/zenn-model/src/types.ts
packages/zenn-model/src/utils.ts

トピック名の文字数をvalidateするようにしました。
Resolves https://github.com/zenn-dev/zenn-editor/issues/544

feat: トピック名の文字数をvalidateするように

---

packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
packages/zenn-cli/src/server/__tests__/preview/app.test.ts
packages/zenn-cli/src/server/app.ts
packages/zenn-cli/src/server/lib/helper.ts

画像パスの参照時にsrcをデコードして読み込むことで画像パスにスペースなどが含まれる場合もプレビューが成功するようにしました。
Resolves https://github.com/zenn-dev/zenn-community/issues/719

fix: プレビュー時に画像パスにスペース(%20)が入っていると「ファイルが存在しません」エラーが発生する

---

packages/zenn-markdown-html/__tests__/highlight.test.ts
packages/zenn-markdown-html/src/utils/md-renderer-fence.ts

コードブロックにおいて、ファイル名にコロンが含まれるケースを考慮してファイル名を抽出します
`html:filename:bar.html` のような形式でファイル名が指定されていた時に、 `html` が拡張子、 `filename:bar.html` がファイル名として抽出されるようになります
（ローカルのzenn-cliで検証）
Resolves https://github.com/zenn-dev/zenn-community/issues/726

fix: ファイル名にコロンが含まれるケースを考慮
